import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-treasury-bank-fee-earnings-credit-audit",
  "engine": "recovery",
  "title": "Treasury Bank Fee & Earnings Credit Audit",
  "shortTitle": "Bank Fee Audit",
  "tagline": "Recalculate bank service fees, usage volumes, earnings credits, and relationship economics",
  "industry": "Corporate Treasury Financial Assurance",
  "uiPort": 4581,
  "apiPort": 5581,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Unsupported treasury service charges recovered and bank relationships optimized using independently verified data",
  "valueNarrative": "Normalize account-analysis statements, AFP codes, fee schedules, usage, balances, earnings credits, wires, ACH, lockbox, and refunds.",
  "calculation": {
    "actualKey": "chargedFees",
    "expectedKey": "supportedFees",
    "actualLabel": "Bank Charged Fees",
    "expectedLabel": "Supported Net Fees",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Bank service, volume, price, balance, and earnings-credit evidence indicate recoverable treasury fees.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("bank-agreement-library","BFA01","Bank agreement library","Reconcile bank agreement library using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed bank agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Bank agreement library Reference","text","BFA01-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("account-and-service-registry","BFA02","Account and service registry","Reconcile account and service registry using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed account and service registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Account and service registry Reference","text","BFA02-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("analysis-statement-ingestion","BFA03","Analysis statement ingestion","Reconcile analysis statement ingestion using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed analysis statement ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Analysis statement ingestion Reference","text","BFA03-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("afp-code-normalization","BFA04","AFP code normalization","Reconcile afp code normalization using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed afp code normalization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","AFP code normalization Reference","text","BFA04-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("unit-price-validation","BFA05","Unit-price validation","Reconcile unit-price validation using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed unit-price validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Unit-price validation Reference","text","BFA05-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("volume-and-usage-validation","BFA06","Volume and usage validation","Reconcile volume and usage validation using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed volume and usage validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Volume and usage validation Reference","text","BFA06-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("duplicate-service-detection","BFA07","Duplicate service detection","Reconcile duplicate service detection using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed duplicate service detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Duplicate service detection Reference","text","BFA07-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("closed-account-fee-detection","BFA08","Closed-account fee detection","Reconcile closed-account fee detection using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed closed-account fee detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Closed-account fee detection Reference","text","BFA08-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("earnings-credit-validation","BFA09","Earnings credit validation","Reconcile earnings credit validation using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed earnings credit validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Earnings credit validation Reference","text","BFA09-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("compensating-balance-calculation","BFA10","Compensating balance calculation","Reconcile compensating balance calculation using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed compensating balance calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Compensating balance calculation Reference","text","BFA10-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("deposit-assessment-review","BFA11","Deposit assessment review","Reconcile deposit assessment review using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed deposit assessment review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Deposit assessment review Reference","text","BFA11-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("wire-ach-and-lockbox-audit","BFA12","Wire ACH and lockbox audit","Reconcile wire ach and lockbox audit using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed wire ach and lockbox audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Wire ACH and lockbox audit Reference","text","BFA12-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("bank-exception-workflow","BFA13","Bank exception workflow","Reconcile bank exception workflow using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed bank exception workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Bank exception workflow Reference","text","BFA13-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("refund-reconciliation","BFA14","Refund reconciliation","Reconcile refund reconciliation using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed refund reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Refund reconciliation Reference","text","BFA14-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("relationship-scorecard","BFA15","Relationship scorecard","Reconcile relationship scorecard using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed relationship scorecard decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Relationship scorecard Reference","text","BFA15-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]}),
feature("account-service-optimization-analytics","BFA16","Account service optimization analytics","Reconcile account service optimization analytics using bank agreements, fee schedules, AFP service codes, analysis statements, account usage, balances, earnings-credit rates, wires, ACH, lockbox activity, and refunds.","Produce a governed account service optimization analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["bankAccount","Bank / Analysis Account","text","Continental Bank / DDA-88412"],["caseReference","Account service optimization analytics Reference","text","BFA16-2026-001"],["chargedFees","Bank Charged Fees","currency",318000],["supportedFees","Supported Net Fees","currency",226500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedFees",subjects:["Primary operating bank","Disbursement account group","Lockbox relationship","Global treasury bank","Acquisition account portfolio"]})
]);
